<?php
/**
 * @file
 * Code for the Pingdom API module.
 */

include_once 'pingdom_api.features.inc';

/**
 * Implements hook_wsclient_service_load.
 */
function pingdom_api_wsclient_service_load($services) {
  $pingdom_credentials = variable_get('pingdom_api_username') . ':' . variable_get('pingdom_api_pass');
  $services['pingdom']->settings['curl options'][CURLOPT_USERPWD] = $pingdom_credentials;
  $pingdom_appkey = variable_get('pingdom_api_appkey');
  $services['pingdom']->settings['curl options'][CURLOPT_HTTPHEADER] = array("App-Key: " . $pingdom_appkey);
}

function pingdom_api_wsclient_get_check_list() {
  $service = wsclient_service_load('pingdom');
  $result = $service->get_check_list();
//  dpm($result);
  return $result;
}

/**
 * Implements hook_menu().
 */
function pingdom_api_menu() {
  $items['admin/config/services/pingdomapi'] = array(
    'title' => 'Pingdom API',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pingdom_api_config_form'),
    'access arguments' =>  array('administer site configuration'),
  );
  return $items;
}

/**
 * Configuration form.
 */
function pingdom_api_config_form($form, &$form_state) {
  $form['authentication'] = array(
    '#type' => 'fieldset',
    '#title' => t('Pingdom API Authentication'),
    '#description' => t('Enter your Pingdom API credentials below. See the <a href="@pingdomapidocs">Pingdom API Documentation</a> for more information.', array('@pingdomapidocs' => 'https://www.pingdom.com/features/api/documentation/')),
  );
  $form['authentication']['user_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Pingdom User Name'),
    '#default_value' => variable_get('pingdom_api_username'),
  );
  $form['authentication']['password'] = array(
    '#type' => 'password',
    '#title' => t('Password'),
    '#default_value' => variable_get('pingdom_api_pass'),
  );
  $form['authentication']['appkey'] = array(
    '#type' => 'textfield',
    '#title' => t('Application Key'),
    '#default_value' => variable_get('pingdom_api_appkey'),
  );
  $form['authentication']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}

/**
 * Submit function for configuration form.
 */
function pingdom_api_config_form_submit($form, &$form_state) {
  variable_set('pingdom_api_username', $form_state['values']['user_name']);
  variable_set('pingdom_api_pass', $form_state['values']['password']);
  variable_set('pingdom_api_appkey', $form_state['values']['appkey']);
}
